# Generated by Django 6.0.1 on 2026-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_salesboardsummary_datasource_devicegroup_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screendesign',
            name='date_filter_mode',
            field=models.CharField(choices=[('current', 'Current Period'), ('yesterday', 'Yesterday'), ('last_week', 'Last Week')], default='current', help_text='Date context for data displayed on this screen', max_length=20),
        ),
        migrations.AddField(
            model_name='screendesign',
            name='store_filter_id',
            field=models.IntegerField(blank=True, help_text='Optional store_id to filter data to a specific store', null=True),
        ),
    ]
