# Generated by Django 6.0.1 on 2026-01-23 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_add_screen_filter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this template', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this template', max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this template', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template is for')),
                ('template_type', models.CharField(choices=[('leaderboard', 'Leaderboard'), ('kpi_dashboard', 'KPI Dashboard'), ('announcement', 'Announcement'), ('custom', 'Custom')], default='custom', help_text='Category of template', max_length=20)),
                ('html_code', models.TextField(blank=True, help_text='HTML code for the template')),
                ('css_code', models.TextField(blank=True, help_text='CSS code for the template')),
                ('js_code', models.TextField(blank=True, help_text='JavaScript code for the template')),
                ('branding_config', models.JSONField(blank=True, default=dict, help_text='Branding settings (colors, fonts, logo URL)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview image for this template', null=True, upload_to='template_thumbnails/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this template prominently in the gallery')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of designs created from this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_design', models.ForeignKey(blank=True, help_text='Original design this template was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='signage.screendesign')),
            ],
            options={
                'verbose_name': 'Screen Template',
                'verbose_name_plural': 'Screen Templates',
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='signage_scr_templat_3d0c49_idx'), models.Index(fields=['-usage_count'], name='signage_scr_usage_c_881740_idx')],
            },
        ),
    ]
