# Generated by Django 6.0.1 on 2026-02-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0004_screentemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalesSummary',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('employee_id', models.IntegerField(null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_username', models.CharField(max_length=200, null=True)),
                ('report_date', models.DateField()),
                ('today_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('today_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('today_invoice_count', models.IntegerField(null=True)),
                ('today_devices_sold', models.IntegerField(null=True)),
                ('today_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_invoice_count', models.IntegerField(null=True)),
                ('mtd_devices_sold', models.IntegerField(null=True)),
                ('mtd_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_profit_target', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_device_target', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_activations_target', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_accessories_target', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_smart_return_target', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mtd_profit_pct_of_target', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mtd_device_pct_of_target', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ly_month_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ly_month_invoiced', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('ly_month_devices_sold', models.IntegerField(null=True)),
                ('ly_month_device_profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Employee Sales Summary',
                'verbose_name_plural': 'Employee Sales Summaries',
                'db_table': 'employee_sales_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='screendesign',
            name='page_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds per page for multi-page designs (e.g., per employee in KPI cards)', null=True),
        ),
    ]
